import Track from '../models/Track.js';
import TrackProgress from '../models/TrackProgress.js';
import Question from '../models/Question.js';
import User from '../models/User.js';

// Categories mapping for fallback
const CATEGORY_PARTNERS = {
  service: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'Accenture', 'Capgemini', 'HCL'],
  product: ['Amazon', 'Google', 'Microsoft', 'Adobe', 'Uber', 'Netflix', 'Meta']
};

/**
 * Helper to fetch unsolved questions for a specific company or fallback partners
 */
const getUnsolvedQuestions = async (userSolvedIds, companyName, category, batchSize = 5) => {
  // Try to find questions from the target company first
  let candidates = await Question.find({
    company: { $regex: new RegExp(companyName, 'i') },
    _id: { $nin: userSolvedIds }
  }).select('_id');

  // If we don't have enough, pull from partner companies in the same category
  if (candidates.length < batchSize && category) {
    const partners = CATEGORY_PARTNERS[category.toLowerCase()] || [];
    const extraCandidates = await Question.find({
      company: { $in: partners },
      _id: { $nin: [...userSolvedIds, ...candidates.map(c => c._id)] }
    }).select('_id');
    candidates = [...candidates, ...extraCandidates];
  }

  // Shuffle and pick batchSize questions
  const shuffled = candidates.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, batchSize).map(c => c._id);
};

/**
 * @desc    Get all tracks with dynamic progress calculations
 * @route   GET /api/tracks
 * @access  Private
 */
export const getTracks = async (req, res) => {
  try {
    const tracks = await Track.find({});
    const user = await User.findById(req.user._id);

    if (!user) {
      return res.status(404).json({ message: 'User not found' });
    }

    const solvedQuestions = user.solvedQuestions.map(id => id.toString());
    const progressList = await TrackProgress.find({ user: user._id });

    // Build map of progress for easy lookup
    const progressMap = {};
    progressList.forEach(p => {
      progressMap[p.track.toString()] = p;
    });

    const response = [];

    for (let track of tracks) {
      let trackQuestions = [];

      if (track.isAutoGenerated) {
        // Look up generated questions from progress cache
        const progress = progressMap[track._id.toString()];
        if (progress && progress.generatedQuestions && progress.generatedQuestions.length > 0) {
          trackQuestions = progress.generatedQuestions.map(id => id.toString());
        } else {
          // If no progress document or cache exists yet, pre-calculate it dynamically
          const generatedIds = await getUnsolvedQuestions(user.solvedQuestions, track.company, track.category, 5);
          trackQuestions = generatedIds.map(id => id.toString());

          // Save to cache
          await TrackProgress.findOneAndUpdate(
            { user: user._id, track: track._id },
            { generatedQuestions: generatedIds },
            { upsert: true, new: true }
          );
        }
      } else {
        trackQuestions = track.questions.map(id => id.toString());
      }

      const totalQuestions = trackQuestions.length;
      const completedQuestions = trackQuestions.filter(id => solvedQuestions.includes(id)).length;
      const progressPercent = totalQuestions > 0 ? Math.round((completedQuestions / totalQuestions) * 100) : 0;

      const progressDoc = progressMap[track._id.toString()];
      const lastAccessed = progressDoc ? progressDoc.lastAccessedQuestion : null;

      response.push({
        _id: track._id,
        title: track.title,
        description: track.description,
        type: track.type,
        category: track.category,
        company: track.company,
        month: track.month,
        isAutoGenerated: track.isAutoGenerated,
        totalQuestions,
        completedQuestions,
        progressPercent,
        lastAccessedQuestion: lastAccessed
      });
    }

    res.json(response);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Get single track details and populated questions
 * @route   GET /api/tracks/:id
 * @access  Private
 */
export const getTrackById = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    const user = await User.findById(req.user._id);
    let trackQuestions = [];

    if (track.isAutoGenerated) {
      // Find or build progress document
      let progress = await TrackProgress.findOne({ user: user._id, track: track._id });
      if (!progress || !progress.generatedQuestions || progress.generatedQuestions.length === 0) {
        const generatedIds = await getUnsolvedQuestions(user.solvedQuestions, track.company, track.category, 5);
        progress = await TrackProgress.findOneAndUpdate(
          { user: user._id, track: track._id },
          { generatedQuestions: generatedIds },
          { upsert: true, new: true }
        );
      }
      
      // Fetch details of generated questions (strip hidden test cases)
      trackQuestions = await Question.find({ _id: { $in: progress.generatedQuestions } }).select('-hiddenTestCases');
      
      // Keep ordering corresponding to the generated batch
      const orderMap = {};
      progress.generatedQuestions.forEach((id, index) => {
        orderMap[id.toString()] = index;
      });
      trackQuestions.sort((a, b) => orderMap[a._id.toString()] - orderMap[b._id.toString()]);
    } else {
      // Fetch details of manually selected questions
      trackQuestions = await Question.find({ _id: { $in: track.questions } }).select('-hiddenTestCases');
      
      // Keep original ordering
      const orderMap = {};
      track.questions.forEach((id, index) => {
        orderMap[id.toString()] = index;
      });
      trackQuestions.sort((a, b) => orderMap[a._id.toString()] - orderMap[b._id.toString()]);
    }

    const solvedQuestions = user.solvedQuestions.map(id => id.toString());
    const questionsResponse = trackQuestions.map(q => ({
      _id: q._id,
      title: q.title,
      difficulty: q.difficulty,
      topic: q.topic,
      company: q.company,
      solved: solvedQuestions.includes(q._id.toString())
    }));

    const progressDoc = await TrackProgress.findOne({ user: user._id, track: track._id });

    res.json({
      track: {
        _id: track._id,
        title: track.title,
        description: track.description,
        type: track.type,
        category: track.category,
        company: track.company,
        month: track.month,
        isAutoGenerated: track.isAutoGenerated
      },
      questions: questionsResponse,
      lastAccessedQuestion: progressDoc ? progressDoc.lastAccessedQuestion : null
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Create a new track
 * @route   POST /api/tracks
 * @access  Private/Admin
 */
export const createTrack = async (req, res) => {
  const { title, description, type, category, company, month, questions, isAutoGenerated } = req.body;

  if (!title || !type) {
    return res.status(400).json({ message: 'Title and Type are required' });
  }

  try {
    const track = new Track({
      title,
      description,
      type,
      category,
      company,
      month,
      questions: questions || [],
      isAutoGenerated: isAutoGenerated || false,
      createdBy: req.user._id
    });

    const createdTrack = await track.save();
    res.status(201).json(createdTrack);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Update an existing track
 * @route   PUT /api/tracks/:id
 * @access  Private/Admin
 */
export const updateTrack = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    const { title, description, category, company, month, questions, isAutoGenerated } = req.body;

    track.title = title || track.title;
    track.description = description !== undefined ? description : track.description;
    track.category = category !== undefined ? category : track.category;
    track.company = company !== undefined ? company : track.company;
    track.month = month !== undefined ? month : track.month;
    track.questions = questions !== undefined ? questions : track.questions;
    track.isAutoGenerated = isAutoGenerated !== undefined ? isAutoGenerated : track.isAutoGenerated;

    const updatedTrack = await track.save();
    res.json(updatedTrack);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Delete a track
 * @route   DELETE /api/tracks/:id
 * @access  Private/Admin
 */
export const deleteTrack = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    // Delete associated progress entries
    await TrackProgress.deleteMany({ track: req.params.id });
    await Track.deleteOne({ _id: req.params.id });

    res.json({ message: 'Track and progress records deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Update last accessed question in a track
 * @route   POST /api/tracks/:id/access
 * @access  Private
 */
export const updateTrackLastAccessed = async (req, res) => {
  const { questionId } = req.body;
  if (!questionId) {
    return res.status(400).json({ message: 'Question ID is required' });
  }

  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    const progress = await TrackProgress.findOneAndUpdate(
      { user: req.user._id, track: track._id },
      { lastAccessedQuestion: questionId },
      { upsert: true, new: true }
    );

    res.json(progress);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
