import Track from '../models/Track.js';
import TrackProgress from '../models/TrackProgress.js';
import Question from '../models/Question.js';
import User from '../models/User.js';

// Categories mapping for fallback
const CATEGORY_PARTNERS = {
  service: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'Accenture', 'Capgemini', 'HCL'],
  product: ['Amazon', 'Google', 'Microsoft', 'Adobe', 'Uber', 'Netflix', 'Meta']
};

/**
 * Helper to fetch unsolved questions for a specific company or fallback partners
 */
const getUnsolvedQuestions = async (userSolvedIds, companyName, category, topicName, batchSize = 5) => {
  let query = {
    domain: 'coding',
    _id: { $nin: userSolvedIds }
  };

  if (topicName) {
    query.topic = { $regex: new RegExp(topicName, 'i') };
  } else if (companyName) {
    query.company = { $regex: new RegExp(companyName, 'i') };
  }

  // Try to find questions matching query first
  let candidates = await Question.find(query).select('_id difficulty');

  // If we don't have enough, pull from partner companies in the same category (only for company queries)
  if (candidates.length < batchSize && category && !topicName) {
    const partners = CATEGORY_PARTNERS[category.toLowerCase()] || [];
    const extraCandidates = await Question.find({
      domain: 'coding',
      company: { $in: partners },
      _id: { $nin: [...userSolvedIds, ...candidates.map(c => c._id)] }
    }).select('_id difficulty');
    candidates = [...candidates, ...extraCandidates];
  }

  // Shuffle candidates to randomize selection
  const shuffled = candidates.sort(() => 0.5 - Math.random());
  
  // Pick the first batchSize questions
  const selected = shuffled.slice(0, batchSize);

  // Sort selected questions from Easy -> Medium -> Hard
  const difficultyOrder = {
    'easy': 1,
    'easy-medium': 2,
    'medium': 3,
    'medium-hard': 4,
    'hard': 5
  };
  selected.sort((a, b) => {
    const diffA = (a.difficulty || 'medium').toLowerCase();
    const diffB = (b.difficulty || 'medium').toLowerCase();
    return (difficultyOrder[diffA] || 3) - (difficultyOrder[diffB] || 3);
  });

  return selected.map(c => c._id);
};

/**
 * @desc    Get all tracks with dynamic progress calculations
 * @route   GET /api/tracks
 * @access  Private
 */
export const getTracks = async (req, res) => {
  try {
    const tracks = await Track.find({});
    const user = req.user ? await User.findById(req.user._id) : null;

    const solvedQuestions = user ? user.solvedQuestions.map(id => id.toString()) : [];
    const progressList = user ? await TrackProgress.find({ user: user._id }) : [];

    // Build map of progress for easy lookup
    const progressMap = {};
    progressList.forEach(p => {
      progressMap[p.track.toString()] = p;
    });

    const response = [];

    for (let track of tracks) {
      let trackQuestions = [];

      if (track.isAutoGenerated) {
        // Look up generated questions from progress cache
        const progress = progressMap[track._id.toString()];
        if (progress && progress.generatedQuestions && progress.generatedQuestions.length > 0) {
          trackQuestions = progress.generatedQuestions.map(id => id.toString());
        } else {
          // If no progress document or cache exists yet, pre-calculate it dynamically
          const solvedIds = user ? user.solvedQuestions : [];
          const generatedIds = await getUnsolvedQuestions(solvedIds, track.company, track.category, track.topic, 5);
          trackQuestions = generatedIds.map(id => id.toString());

          // Save to cache only if user is logged in
          if (user) {
            await TrackProgress.findOneAndUpdate(
              { user: user._id, track: track._id },
              { generatedQuestions: generatedIds },
              { upsert: true, new: true }
            );
          }
        }
      } else {
        trackQuestions = track.questions.map(id => id.toString());
      }

      const totalQuestions = trackQuestions.length;
      const completedQuestions = trackQuestions.filter(id => solvedQuestions.includes(id)).length;
      const progressPercent = totalQuestions > 0 ? Math.round((completedQuestions / totalQuestions) * 100) : 0;

      const progressDoc = progressMap[track._id.toString()];
      const lastAccessed = progressDoc ? progressDoc.lastAccessedQuestion : null;

      response.push({
        _id: track._id,
        title: track.title,
        description: track.description,
        type: track.type,
        category: track.category,
        company: track.company,
        topic: track.topic,
        month: track.month,
        isAutoGenerated: track.isAutoGenerated,
        totalQuestions,
        completedQuestions,
        progressPercent,
        lastAccessedQuestion: lastAccessed
      });
    }

    res.json(response);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Get single track details and populated questions
 * @route   GET /api/tracks/:id
 * @access  Private
 */
export const getTrackById = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    const user = req.user ? await User.findById(req.user._id) : null;
    let trackQuestions = [];

    if (track.isAutoGenerated) {
      // Find or build progress document
      let progress = user ? await TrackProgress.findOne({ user: user._id, track: track._id }) : null;
      if (!progress || !progress.generatedQuestions || progress.generatedQuestions.length === 0) {
        const solvedIds = user ? user.solvedQuestions : [];
        const generatedIds = await getUnsolvedQuestions(solvedIds, track.company, track.category, track.topic, 5);
        
        if (user) {
          progress = await TrackProgress.findOneAndUpdate(
            { user: user._id, track: track._id },
            { generatedQuestions: generatedIds },
            { upsert: true, new: true }
          );
        } else {
          progress = { generatedQuestions: generatedIds };
        }
      }
      
      // Fetch details of generated questions (strip hidden test cases)
      trackQuestions = await Question.find({ _id: { $in: progress.generatedQuestions } }).select('-hiddenTestCases');
      
      // Keep ordering corresponding to the generated batch
      const orderMap = {};
      progress.generatedQuestions.forEach((id, index) => {
        orderMap[id.toString()] = index;
      });
      trackQuestions.sort((a, b) => orderMap[a._id.toString()] - orderMap[b._id.toString()]);
    } else {
      // Fetch details of manually selected questions
      trackQuestions = await Question.find({ _id: { $in: track.questions } }).select('-hiddenTestCases');
      
      // Keep original ordering
      const orderMap = {};
      track.questions.forEach((id, index) => {
        orderMap[id.toString()] = index;
      });
      trackQuestions.sort((a, b) => orderMap[a._id.toString()] - orderMap[b._id.toString()]);
    }

    const solvedQuestions = user ? user.solvedQuestions.map(id => id.toString()) : [];
    const questionsResponse = trackQuestions.map(q => ({
      _id: q._id,
      title: q.title,
      slug: q.slug,
      difficulty: q.difficulty,
      topic: q.topic,
      company: q.company,
      solved: solvedQuestions.includes(q._id.toString())
    }));

    const progressDoc = user ? await TrackProgress.findOne({ user: user._id, track: track._id }) : null;

    res.json({
      track: {
        _id: track._id,
        title: track.title,
        description: track.description,
        type: track.type,
        category: track.category,
        company: track.company,
        topic: track.topic,
        month: track.month,
        isAutoGenerated: track.isAutoGenerated
      },
      questions: questionsResponse,
      lastAccessedQuestion: progressDoc ? progressDoc.lastAccessedQuestion : null
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Create a new track
 * @route   POST /api/tracks
 * @access  Private/Admin
 */
export const createTrack = async (req, res) => {
  const { title, description, type, category, company, month, questions, isAutoGenerated } = req.body;

  if (!title || !type) {
    return res.status(400).json({ message: 'Title and Type are required' });
  }

  try {
    const track = new Track({
      title,
      description,
      type,
      category,
      company,
      month,
      questions: questions || [],
      isAutoGenerated: isAutoGenerated || false,
      createdBy: req.user._id
    });

    const createdTrack = await track.save();
    res.status(201).json(createdTrack);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Update an existing track
 * @route   PUT /api/tracks/:id
 * @access  Private/Admin
 */
export const updateTrack = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    const { title, description, category, company, month, questions, isAutoGenerated } = req.body;

    track.title = title || track.title;
    track.description = description !== undefined ? description : track.description;
    track.category = category !== undefined ? category : track.category;
    track.company = company !== undefined ? company : track.company;
    track.month = month !== undefined ? month : track.month;
    track.questions = questions !== undefined ? questions : track.questions;
    track.isAutoGenerated = isAutoGenerated !== undefined ? isAutoGenerated : track.isAutoGenerated;

    const updatedTrack = await track.save();
    res.json(updatedTrack);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Delete a track
 * @route   DELETE /api/tracks/:id
 * @access  Private/Admin
 */
export const deleteTrack = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    // Delete associated progress entries
    await TrackProgress.deleteMany({ track: req.params.id });
    await Track.deleteOne({ _id: req.params.id });

    res.json({ message: 'Track and progress records deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Update last accessed question in a track
 * @route   POST /api/tracks/:id/access
 * @access  Private
 */
export const updateTrackLastAccessed = async (req, res) => {
  const { questionId } = req.body;
  if (!questionId) {
    return res.status(400).json({ message: 'Question ID is required' });
  }

  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    const progress = await TrackProgress.findOneAndUpdate(
      { user: req.user._id, track: track._id },
      { lastAccessedQuestion: questionId },
      { upsert: true, new: true }
    );

    res.json(progress);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * @desc    Reset user progress on a track (regenerates new questions next time)
 * @route   POST /api/tracks/:id/reset
 * @access  Private
 */
export const resetTrackProgress = async (req, res) => {
  try {
    const track = await Track.findById(req.params.id);
    if (!track) {
      return res.status(404).json({ message: 'Track not found' });
    }

    await TrackProgress.findOneAndDelete({ user: req.user._id, track: track._id });
    res.json({ message: 'Track progress reset successfully.' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
