import Track from '../models/Track.js';
import User from '../models/User.js';
import Question from '../models/Question.js';

export const seedTracks = async () => {
  try {
    // Clear existing tracks to clean-seed the new auto-discovered lists
    await Track.deleteMany({});
    console.log('Cleared existing practice tracks.');

    const adminUser = await User.findOne({ role: 'admin' });
    const creatorId = adminUser ? adminUser._id : null;

    // Discover all unique companies and topics in the database
    const companies = await Question.distinct('company', { domain: 'coding' });
    const topics = await Question.distinct('topic', { domain: 'coding' });

    console.log(`Found ${companies.length} unique companies and ${topics.length} unique topics in coding questions.`);

    const tracksToSeed = [];

    // 1. Programmatically seed Company tracks
    companies.forEach(company => {
      if (!company || company.trim() === '') return;
      // Determine service vs product category
      const serviceCompanies = ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'Accenture', 'Capgemini', 'HCL'];
      const category = serviceCompanies.includes(company) ? 'service' : 'product';

      tracksToSeed.push({
        title: `${company} Preparation Roadmap`,
        description: `Master the coding challenges frequently featured in ${company} exams. Auto-generates unsolved ${company} questions sequentially.`,
        type: 'company',
        category,
        company,
        isAutoGenerated: true,
        createdBy: creatorId
      });
    });

    // 2. Programmatically seed Topic tracks
    topics.forEach(topic => {
      if (!topic || topic.trim() === '') return;
      tracksToSeed.push({
        title: `${topic} Practice Path`,
        description: `Master basic to advanced challenges on ${topic} systematically. Auto-generates unsolved ${topic} questions sequentially.`,
        type: 'topic',
        topic,
        isAutoGenerated: true,
        createdBy: creatorId
      });
    });

    if (tracksToSeed.length > 0) {
      await Track.insertMany(tracksToSeed);
      console.log(`Successfully seeded ${tracksToSeed.length} practice tracks!`);
    } else {
      console.log('No tracks found to seed.');
    }
  } catch (error) {
    console.error('Error seeding tracks:', error.message);
    throw error;
  }
};
