import Track from '../models/Track.js';
import User from '../models/User.js';

export const seedTracks = async () => {
  try {
    // Clear existing tracks to clean-seed the new combined list
    await Track.deleteMany({});
    console.log('Cleared existing practice tracks.');

    console.log('Seeding Practice Tracks...');

    const adminUser = await User.findOne({ role: 'admin' });
    const creatorId = adminUser ? adminUser._id : null;

    const tracksToSeed = [
      {
        title: 'TCS NQT Preparation Roadmap',
        description: 'Master the coding challenges frequently featured in TCS NQT exams. Auto-generates unsolved TCS NQT questions sequentially.',
        type: 'company',
        category: 'service',
        company: 'TCS',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Infosys DSE/SP Prep Roadmap',
        description: 'A curated roadmap targeting the Specialist Programmer (SP) and Digital Specialist Engineer (DSE) recruitment assessments.',
        type: 'company',
        category: 'service',
        company: 'Infosys',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Wipro Elite Preparation Roadmap',
        description: 'Ace Wipro Elite NLTH coding assessments. Focuses on core structures, arrays, and standard algorithm problems.',
        type: 'company',
        category: 'service',
        company: 'Wipro',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Accenture ASE/FSE Prep Roadmap',
        description: 'Comprehensive study path designed for the Associate Software Engineer (ASE) and Full Stack Engineer (FSE) coding shifts.',
        type: 'company',
        category: 'service',
        company: 'Accenture',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Cognizant GenC Prep Roadmap',
        description: 'Get ready for Cognizant GenC and GenC Next programming rounds. Includes basic string processing and array sorting questions.',
        type: 'company',
        category: 'service',
        company: 'Cognizant',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      // Topic Tracks
      {
        title: 'Arrays & Sorting Practice Path',
        description: 'Master basic to advanced array manipulation, search algorithms, and sorting techniques sequentially.',
        type: 'topic',
        topic: 'Arrays',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Strings & Pattern Matching Practice Path',
        description: 'Practice string traversal, reverse operations, parsing, and complex substring searches.',
        type: 'topic',
        topic: 'Strings',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Dynamic Programming Practice Path',
        description: 'Solve optimization problems and subset sum challenges sequentially. Learn memoization and tabulation.',
        type: 'topic',
        topic: 'Dynamic Programming',
        isAutoGenerated: true,
        createdBy: creatorId
      },
      {
        title: 'Mathematical Coding Practice Path',
        description: 'Master prime numbers, modular arithmetic, GCD, and numerical base conversions.',
        type: 'topic',
        topic: 'Math',
        isAutoGenerated: true,
        createdBy: creatorId
      }
    ];

    await Track.insertMany(tracksToSeed);
    console.log('Practice Tracks successfully seeded!');
  } catch (error) {
    console.error('Error seeding tracks:', error.message);
    throw error;
  }
};
