import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import * as questionService from '../services/questionService';
import * as trackService from '../services/trackService';
import * as feedbackService from '../services/feedbackService';
import * as resourceService from '../services/resourceService';
import AdminQuestionForm from './AdminQuestionForm';
import { 
  Plus, Edit2, Trash2, ShieldAlert, Award, Tag, Settings, 
  Users, BookOpen, Send, Activity, LayoutDashboard, ChevronRight,
  Compass, Calendar, ExternalLink, MessageSquare, Bug, Check,
  Database, Server, Network, Layers, FileText, FolderOpen, Link2, Building2
} from 'lucide-react';
import SEO from '../components/SEO';

const AdminDashboard = () => {
  const navigate = useNavigate();
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState('overview'); // 'overview', 'questions', 'add_question', 'manage_tracks', 'feedback'
  const [editQuestionId, setEditQuestionId] = useState(null);

  // Feedback Management States
  const [feedbacks, setFeedbacks] = useState([]);
  const [feedbackLoading, setFeedbackLoading] = useState(false);
  const [feedbackError, setFeedbackError] = useState('');
  const [feedbackFilter, setFeedbackFilter] = useState('all'); // 'all', 'feedback', 'bug', 'general'
  
  // Track Management States
  const [tracks, setTracks] = useState([]);
  const [tracksLoading, setTracksLoading] = useState(false);
  const [tracksError, setTracksError] = useState('');
  
  const [editTrackId, setEditTrackId] = useState(null);
  const [isTrackFormActive, setIsTrackFormActive] = useState(false);
  const [trackTitle, setTrackTitle] = useState('');
  const [trackDescription, setTrackDescription] = useState('');
  const [trackType, setTrackType] = useState('company'); // 'company', 'topic'
  const [trackCategory, setTrackCategory] = useState('service'); // 'service', 'product'
  const [trackCompany, setTrackCompany] = useState('');
  const [trackMonth, setTrackMonth] = useState('');
  const [trackIsAutoGenerated, setTrackIsAutoGenerated] = useState(false);
  const [trackQuestions, setTrackQuestions] = useState([]);
  const [trackQuestionSearch, setTrackQuestionSearch] = useState('');

  // Search state
  const [searchQuery, setSearchQuery] = useState('');
  const [domainFilter, setDomainFilter] = useState('all');

  const [stats, setStats] = useState({
    totalUsers: 0,
    totalQuestions: 0,
    totalSubmissions: 0,
    liveUsers: 1
  });
  const [statsLoading, setStatsLoading] = useState(true);

  // Resource Management States
  const [resCategories, setResCategories] = useState([]);
  const [resLoading, setResLoading] = useState(false);
  const [resError, setResError] = useState('');
  const [resFormActive, setResFormActive] = useState(false);
  const [editResId, setEditResId] = useState(null);
  const [resTitle, setResTitle] = useState('');
  const [resIcon, setResIcon] = useState('Database');
  const [resDriveLink, setResDriveLink] = useState('');
  const [resSaveMsg, setResSaveMsg] = useState('');

  useEffect(() => {
    fetchStats();
    fetchTracks();
  }, []);

  useEffect(() => {
    fetchQuestions(domainFilter);
  }, [domainFilter]);

  const fetchResCategories = async () => {
    setResLoading(true);
    setResError('');
    try {
      const data = await resourceService.getCategories();
      setResCategories(data);
    } catch (err) {
      setResError('Could not fetch resources.');
    } finally {
      setResLoading(false);
    }
  };

  const handleSaveRes = async (e) => {
    e.preventDefault();
    if (!resTitle.trim()) { alert('Title is required'); return; }
    try {
      const payload = { title: resTitle, icon: resIcon, driveFolderLink: resDriveLink };
      if (editResId) {
        await resourceService.updateCategory(editResId, payload);
      } else {
        await resourceService.createCategory(payload);
      }
      setResFormActive(false);
      setEditResId(null);
      setResTitle('');
      setResIcon('Database');
      setResDriveLink('');
      fetchResCategories();
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to save resource.');
    }
  };

  const handleEditRes = (r) => {
    setEditResId(r._id);
    setResTitle(r.title);
    setResIcon(r.icon || 'Database');
    setResDriveLink(r.driveFolderLink || '');
    setResFormActive(true);
  };

  const handleDeleteRes = async (id, title) => {
    if (window.confirm(`Delete resource "${title}"?`)) {
      try {
        await resourceService.deleteCategory(id);
        fetchResCategories();
      } catch (err) {
        alert('Delete failed.');
      }
    }
  };

  const fetchStats = async () => {
    setStatsLoading(true);
    try {
      const data = await questionService.getAdminStats();
      setStats(data);
    } catch (err) {
      console.error('Could not load statistics', err);
    } finally {
      setStatsLoading(false);
    }
  };

  const fetchFeedback = async () => {
    setFeedbackLoading(true);
    setFeedbackError('');
    try {
      const data = await feedbackService.getAllFeedback();
      setFeedbacks(data);
    } catch (err) {
      console.error(err);
      setFeedbackError('Could not retrieve user feedback logs.');
    } finally {
      setFeedbackLoading(false);
    }
  };

  const handleStatusChange = async (id, newStatus) => {
    try {
      await feedbackService.updateFeedbackStatus(id, newStatus);
      setFeedbacks(prev => 
        prev.map(item => item._id === id ? { ...item, status: newStatus } : item)
      );
    } catch (err) {
      console.error(err);
      alert('Failed to update feedback status.');
    }
  };

  const handleDeleteFeedback = async (id) => {
    if (window.confirm('Are you sure you want to delete this feedback ticket?')) {
      try {
        await feedbackService.deleteFeedback(id);
        setFeedbacks(prev => prev.filter(item => item._id !== id));
      } catch (err) {
        console.error(err);
        alert('Failed to delete feedback ticket.');
      }
    }
  };

  const renderAreaChart = () => {
    const trend = stats.userRegistrationTrend || [];
    if (!trend.length) {
      return (
        <div className="flex flex-col items-center justify-center h-full text-slate-500 space-y-2">
          <div className="animate-spin rounded-full h-6 w-6 border-t-2 border-b-2 border-accentBlue"></div>
          <span className="text-[10px] uppercase font-bold tracking-wider">Loading trend...</span>
        </div>
      );
    }

    const counts = trend.map(t => t.count);
    const maxCount = Math.max(...counts, 10);
    const minCount = Math.min(...counts, 0);

    const points = trend.map((t, i) => {
      const x = (i * 500) / (trend.length - 1);
      const ratio = (t.count - minCount) / ((maxCount - minCount) || 1);
      const y = 165 - ratio * 135; // Fits nicely in 200px height
      return { x, y, label: t.label, count: t.count };
    });

    let areaPath = `M ${points[0].x} 165`;
    let linePath = `M ${points[0].x} ${points[0].y}`;

    for (let i = 1; i < points.length; i++) {
      linePath += ` L ${points[i].x} ${points[i].y}`;
    }

    areaPath += linePath.substring(1) + ` L ${points[points.length - 1].x} 165 Z`;

    return (
      <svg viewBox="0 0 500 200" width="100%" height="100%" className="overflow-visible select-none">
        <defs>
          <linearGradient id="regAreaGrad" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#6366F1" stopOpacity="0.35" />
            <stop offset="100%" stopColor="#6366F1" stopOpacity="0" />
          </linearGradient>
        </defs>
        {/* Horizontal grid lines */}
        <line x1="0" y1="165" x2="500" y2="165" stroke="var(--color-border)" strokeWidth="1" opacity="0.2" />
        <line x1="0" y1="115" x2="500" y2="115" stroke="var(--color-border)" strokeWidth="1" opacity="0.15" strokeDasharray="4" />
        <line x1="0" y1="65" x2="500" y2="65" stroke="var(--color-border)" strokeWidth="1" opacity="0.15" strokeDasharray="4" />
        <line x1="0" y1="15" x2="500" y2="15" stroke="var(--color-border)" strokeWidth="1" opacity="0.15" strokeDasharray="4" />

        {/* Area fill path */}
        <path d={areaPath} fill="url(#regAreaGrad)" />
        
        {/* Line path */}
        <path d={linePath} fill="transparent" stroke="#6366F1" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" />

        {/* Node points and tooltips */}
        {points.map((pt, i) => (
          <g key={i}>
            <circle cx={pt.x} cy={pt.y} r="5" fill="#6366F1" stroke="#1e293b" strokeWidth="2.5" />
            {(i === 0 || i === Math.floor(points.length / 2) || i === points.length - 1) && (
              <text
                x={pt.x}
                y={pt.y - 12}
                fill="#f8fafc"
                stroke="#111827"
                strokeWidth="3.5"
                paintOrder="stroke fill"
                fontSize="9.5"
                fontWeight="black"
                textAnchor={i === 0 ? 'start' : i === points.length - 1 ? 'end' : 'middle'}
              >
                {pt.count} Users
              </text>
            )}
            <text
              x={pt.x}
              y="185"
              fill="var(--color-text-muted)"
              fontSize="9"
              fontWeight="bold"
              textAnchor={i === 0 ? 'start' : i === points.length - 1 ? 'end' : 'middle'}
            >
              {pt.label}
            </text>
          </g>
        ))}
      </svg>
    );
  };

  const renderBarChart = () => {
    const share = stats.languageShare || { cpp: 15, java: 10, python: 20 };
    const totalSub = share.cpp + share.java + share.python || 1;

    const cppPct = Math.round((share.cpp / totalSub) * 100);
    const javaPct = Math.round((share.java / totalSub) * 100);
    const pythonPct = Math.round((share.python / totalSub) * 100);

    const cppH = (cppPct / 100) * 140;
    const javaH = (javaPct / 100) * 140;
    const pythonH = (pythonPct / 100) * 140;

    return (
      <svg viewBox="0 0 400 200" width="100%" height="100%" className="overflow-visible select-none">
        {/* Horizontal grid lines */}
        <line x1="40" y1="160" x2="380" y2="160" stroke="var(--color-border)" opacity="0.25" strokeWidth="1" />
        <line x1="40" y1="110" x2="380" y2="110" stroke="var(--color-border)" opacity="0.15" strokeWidth="1" strokeDasharray="4" />
        <line x1="40" y1="60" x2="380" y2="60" stroke="var(--color-border)" opacity="0.15" strokeWidth="1" strokeDasharray="4" />
        <line x1="40" y1="10" x2="380" y2="10" stroke="var(--color-border)" opacity="0.15" strokeWidth="1" strokeDasharray="4" />

        {/* C++ Bar */}
        <rect x="70" y={160 - cppH} width="45" height={cppH} rx="6" fill="#4f46e5" className="hover:opacity-85 transition-all duration-300 cursor-pointer shadow-md" />
        <text x="92.5" y={150 - cppH} fill="#f8fafc" stroke="#111827" strokeWidth="3.5" paintOrder="stroke fill" fontSize="9.5" fontWeight="black" textAnchor="middle">{cppPct}% ({share.cpp})</text>
        <text x="92.5" y="180" fill="var(--color-text-muted)" fontSize="9" fontWeight="bold" textAnchor="middle">C++</text>

        {/* Java Bar */}
        <rect x="180" y={160 - javaH} width="45" height={javaH} rx="6" fill="#6366f1" className="hover:opacity-85 transition-all duration-300 cursor-pointer shadow-md" />
        <text x="202.5" y={150 - javaH} fill="#f8fafc" stroke="#111827" strokeWidth="3.5" paintOrder="stroke fill" fontSize="9.5" fontWeight="black" textAnchor="middle">{javaPct}% ({share.java})</text>
        <text x="202.5" y="180" fill="var(--color-text-muted)" fontSize="9" fontWeight="bold" textAnchor="middle">Java</text>

        {/* Python Bar */}
        <rect x="295" y={160 - pythonH} width="45" height={pythonH} rx="6" fill="#818cf8" className="hover:opacity-85 transition-all duration-300 cursor-pointer shadow-md" />
        <text x="317.5" y={150 - pythonH} fill="#f8fafc" stroke="#111827" strokeWidth="3.5" paintOrder="stroke fill" fontSize="9.5" fontWeight="black" textAnchor="middle">{pythonPct}% ({share.python})</text>
        <text x="317.5" y="180" fill="var(--color-text-muted)" fontSize="9" fontWeight="bold" textAnchor="middle">Python 3</text>
      </svg>
    );
  };

  const fetchQuestions = async (domain = domainFilter) => {
    setLoading(true);
    setError('');
    try {
      const data = await questionService.getQuestions({ domain });
      setQuestions(data);
    } catch (err) {
      console.error(err);
      setError('Could not download question logs. Verify server console.');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id, title) => {
    if (window.confirm(`Are you sure you want to permanently delete "${title}"? This action cannot be undone.`)) {
      try {
        await questionService.deleteQuestion(id);
        setQuestions((prev) => prev.filter((q) => q._id !== id));
        fetchStats(); // Update question count
      } catch (err) {
        console.error(err);
        alert(err.response?.data?.message || 'Delete operation failed.');
      }
    }
  };

  const handleEdit = (id) => {
    const question = questions.find(q => q._id === id);
    if (question && question.kind === 'MCQQuestion') {
      navigate(`/admin/mcq/edit/${id}`);
    } else if (question && question.kind === 'VerbalQuestion') {
      navigate(`/admin/verbal/edit/${id}`);
    } else {
      setEditQuestionId(id);
      setActiveTab('add_question');
    }
  };

  const fetchTracks = async () => {
    setTracksLoading(true);
    setTracksError('');
    try {
      const data = await trackService.getTracks();
      setTracks(data);
    } catch (err) {
      console.error(err);
      setTracksError('Could not retrieve practice tracks.');
    } finally {
      setTracksLoading(false);
    }
  };

  const handleDeleteTrack = async (id, title) => {
    if (window.confirm(`Are you sure you want to permanently delete track "${title}"? All associated student progress will be lost.`)) {
      try {
        await trackService.deleteTrack(id);
        setTracks((prev) => prev.filter((t) => t._id !== id));
      } catch (err) {
        console.error(err);
        alert(err.response?.data?.message || 'Delete operation failed.');
      }
    }
  };

  const handleEditTrackClick = async (track) => {
    try {
      const fullTrackData = await trackService.getTrackById(track._id);
      setEditTrackId(track._id);
      setTrackTitle(fullTrackData.track.title);
      setTrackDescription(fullTrackData.track.description || '');
      setTrackType(fullTrackData.track.type);
      setTrackCategory(fullTrackData.track.category || 'service');
      setTrackCompany(fullTrackData.track.company || '');
      setTrackMonth(fullTrackData.track.month || '');
      setTrackIsAutoGenerated(fullTrackData.track.isAutoGenerated || false);
      setTrackQuestions(fullTrackData.questions.map(q => q._id));
      setIsTrackFormActive(true);
    } catch (err) {
      console.error(err);
      alert('Could not retrieve detailed track information.');
    }
  };

  const handleSaveTrack = async (e) => {
    e.preventDefault();
    if (!trackTitle.trim()) {
      alert('Track Title is required');
      return;
    }
    if (!trackType) {
      alert('Track Type is required');
      return;
    }

    const trackData = {
      title: trackTitle,
      description: trackDescription,
      type: trackType,
      category: trackType === 'company' ? trackCategory : undefined,
      company: trackType === 'company' ? trackCompany : undefined,
      month: trackType === 'company' ? trackMonth : undefined,
      isAutoGenerated: trackType === 'company' ? trackIsAutoGenerated : false,
      questions: (trackType === 'topic' || !trackIsAutoGenerated) ? trackQuestions : []
    };

    try {
      if (editTrackId) {
        await trackService.updateTrack(editTrackId, trackData);
      } else {
        await trackService.createTrack(trackData);
      }
      setIsTrackFormActive(false);
      setEditTrackId(null);
      fetchTracks();
    } catch (err) {
      console.error(err);
      alert(err.response?.data?.message || 'Failed to save track.');
    }
  };

  const handleCreateTrackClick = () => {
    setEditTrackId(null);
    setTrackTitle('');
    setTrackDescription('');
    setTrackType('company');
    setTrackCategory('service');
    setTrackCompany('');
    setTrackMonth('');
    setTrackIsAutoGenerated(false);
    setTrackQuestions([]);
    setIsTrackFormActive(true);
  };

  const getDifficultyColor = (diff) => {
    switch (diff) {
      case 'Easy': return 'text-emerald-400 border-emerald-500/25 bg-emerald-500/10';
      case 'Easy-Medium': return 'text-teal-400 border-teal-500/25 bg-teal-500/10';
      case 'Medium': return 'text-amber-400 border-amber-500/25 bg-amber-500/10';
      case 'Medium-Hard': return 'text-orange-400 border-orange-500/25 bg-orange-500/10';
      case 'Hard': return 'text-rose-400 border-rose-500/25 bg-rose-500/10';
      default: return 'text-slate-400 border-slate-500/25 bg-slate-500/10';
    }
  };

  // Filter questions based on search query
  const filteredQuestions = questions.filter((q) =>
    (q.title || q.content?.statement || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
    (q.topic || '').toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="h-[calc(100vh-73px)] flex bg-darkBg text-slate-100 overflow-hidden">
      <SEO
        title="Admin Control Center"
        description="Administrative panel for NQTCoder. Manage questions, learning tracks, and platform settings."
        path="/admin"
        noIndex={true}
      />
      
      {/* 1. Left Sidebar Navigation Panel */}
      <aside className="w-64 bg-darkCard border-r border-darkBorder flex flex-col shrink-0">
        
        {/* Navigation Options */}
        <div className="flex-grow p-4 space-y-2 pt-5">

          <button
            onClick={() => {
              setEditQuestionId(null);
              setActiveTab('overview');
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border ${
              activeTab === 'overview'
                ? 'bg-accentBlue border-accentBlue text-white shadow-lg shadow-accentBlue/20'
                : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
            }`}
          >
            <div className="flex items-center space-x-3">
              <LayoutDashboard className="w-4 h-4" />
              <span>Dashboard</span>
            </div>
            <ChevronRight className={`w-3.5 h-3.5 opacity-60 ${activeTab === 'overview' ? 'block' : 'hidden'}`} />
          </button>

          <button
            onClick={() => {
              setEditQuestionId(null);
              setActiveTab('questions');
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border ${
              activeTab === 'questions'
                ? 'bg-accentBlue border-accentBlue text-white shadow-lg shadow-accentBlue/20'
                : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
            }`}
          >
            <div className="flex items-center space-x-3">
              <BookOpen className="w-4 h-4" />
              <span>Manage Questions</span>
            </div>
            <ChevronRight className={`w-3.5 h-3.5 opacity-60 ${activeTab === 'questions' ? 'block' : 'hidden'}`} />
          </button>

          <button
            onClick={() => {
              setEditQuestionId(null);
              setEditTrackId(null);
              setIsTrackFormActive(false);
              setActiveTab('manage_tracks');
              fetchTracks();
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border ${
              activeTab === 'manage_tracks'
                ? 'bg-accentBlue border-accentBlue text-white shadow-lg shadow-accentBlue/20'
                : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
            }`}
          >
            <div className="flex items-center space-x-3">
              <Compass className="w-4 h-4" />
              <span>Manage Tracks</span>
            </div>
            <ChevronRight className={`w-3.5 h-3.5 opacity-60 ${activeTab === 'manage_tracks' ? 'block' : 'hidden'}`} />
          </button>

          <button
            onClick={() => {
              setEditQuestionId(null);
              setActiveTab('add_question');
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border ${
              activeTab === 'add_question' && !editQuestionId
                ? 'bg-accentBlue border-accentBlue text-white shadow-lg shadow-accentBlue/20'
                : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
            }`}
          >
            <div className="flex items-center space-x-3">
              <Plus className="w-4 h-4" />
              <span>Add Challenge</span>
            </div>
            <ChevronRight className={`w-3.5 h-3.5 opacity-60 ${activeTab === 'add_question' && !editQuestionId ? 'block' : 'hidden'}`} />
          </button>

          <button
            onClick={() => {
              navigate('/admin/mcq/new');
            }}
            className="w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60"
          >
            <div className="flex items-center space-x-3">
              <Plus className="w-4 h-4" />
              <span>Add MCQ</span>
            </div>
            <ChevronRight className="w-3.5 h-3.5 opacity-60 hidden" />
          </button>

          <button
            onClick={() => {
              navigate('/admin/verbal/new');
            }}
            className="w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60"
          >
            <div className="flex items-center space-x-3">
              <Plus className="w-4 h-4" />
              <span>Add Verbal</span>
            </div>
            <ChevronRight className="w-3.5 h-3.5 opacity-60 hidden" />
          </button>

          <button
            onClick={() => {
              setEditQuestionId(null);
              setActiveTab('feedback');
              fetchFeedback();
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border ${
              activeTab === 'feedback'
                ? 'bg-accentBlue border-accentBlue text-white shadow-lg shadow-accentBlue/20'
                : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
            }`}
          >
            <div className="flex items-center space-x-3">
              <MessageSquare className="w-4 h-4" />
              <span>User Feedback</span>
            </div>
            <ChevronRight className={`w-3.5 h-3.5 opacity-60 ${activeTab === 'feedback' ? 'block' : 'hidden'}`} />
          </button>

          <button
            onClick={() => {
              setEditQuestionId(null);
              setActiveTab('manage_resources');
              fetchResCategories();
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border ${
              activeTab === 'manage_resources'
                ? 'bg-accentBlue border-accentBlue text-white shadow-lg shadow-accentBlue/20'
                : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
            }`}
          >
            <div className="flex items-center space-x-3">
              <FolderOpen className="w-4 h-4" />
              <span>Manage Resources</span>
            </div>
            <ChevronRight className={`w-3.5 h-3.5 opacity-60 ${activeTab === 'manage_resources' ? 'block' : 'hidden'}`} />
          </button>

          <button
            onClick={() => navigate('/admin/company-guides')}
            className="w-full flex items-center justify-between px-4 py-3 rounded-xl text-xs font-black tracking-wider uppercase transition-all border bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60"
          >
            <div className="flex items-center space-x-3">
              <Building2 className="w-4 h-4" />
              <span>Company Guides</span>
            </div>
            <ChevronRight className="w-3.5 h-3.5 opacity-60 hidden" />
          </button>
        </div>

        {/* View Site link */}
        <div className="p-4 border-t border-darkBorder">
          <Link
            to="/"
            className="w-full flex items-center justify-center space-x-2 py-2.5 rounded-xl border border-darkBorder hover:border-accentBlue/30 text-xs font-bold uppercase tracking-wider text-slate-400 hover:text-accentBlue hover:bg-accentBlue/5 transition-all"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            <span>View Site</span>
          </Link>
        </div>

      </aside>

      {/* 2. Main content area */}
      <main className="flex-grow p-8 overflow-y-auto space-y-8 max-w-7xl">
        
        {/* VIEW 1: Overview Dashboard tab */}
        {activeTab === 'overview' && (
          <div className="space-y-8">
            <div className="border-b border-darkBorder pb-4">
              <h1 className="text-3xl font-black text-white tracking-wide">Admin Dashboard</h1>
              <p className="text-xs text-slate-400 mt-0.5">Real-time statistics, registered students, and compiler execution charts</p>
            </div>

            {/* Metrics cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {/* Card 1: Users */}
              <div className="bg-darkCard border border-darkBorder p-5 rounded-lg flex items-center justify-between shadow-md relative overflow-hidden group hover:border-accentBlue/30 transition-all">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Total Students</span>
                  <div className="text-3xl font-extrabold text-white">
                    {statsLoading ? '...' : stats.totalUsers}
                  </div>
                </div>
                <div className="bg-accentBlue/10 p-3 rounded-md border border-accentBlue/25 text-accentBlue group-hover:bg-accentBlue/20 transition-all">
                  <Users className="w-6 h-6" />
                </div>
              </div>

              {/* Card 2: Questions */}
              <div className="bg-darkCard border border-darkBorder p-5 rounded-lg flex items-center justify-between shadow-md relative overflow-hidden group hover:border-accentBlue/30 transition-all">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Challenges Seeded</span>
                  <div className="text-3xl font-extrabold text-white">
                    {statsLoading ? '...' : stats.totalQuestions}
                  </div>
                </div>
                <div className="bg-accentBlue/10 p-3 rounded-md border border-accentBlue/25 text-accentBlue group-hover:bg-accentBlue/20 transition-all">
                  <BookOpen className="w-6 h-6" />
                </div>
              </div>

              {/* Card 3: Submissions */}
              <div className="bg-darkCard border border-darkBorder p-5 rounded-lg flex items-center justify-between shadow-md relative overflow-hidden group hover:border-accentBlue/30 transition-all">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Compiler Evaluated</span>
                  <div className="text-3xl font-extrabold text-white">
                    {statsLoading ? '...' : stats.totalSubmissions}
                  </div>
                </div>
                <div className="bg-accentBlue/10 p-3 rounded-md border border-accentBlue/25 text-accentBlue group-hover:bg-accentBlue/20 transition-all">
                  <Send className="w-6 h-6" />
                </div>
              </div>

              {/* Card 4: Live active users */}
              <div className="bg-darkCard border border-darkBorder p-5 rounded-lg flex items-center justify-between shadow-md relative overflow-hidden group hover:border-accentBlue/30 transition-all">
                <div className="space-y-1">
                  <div className="flex items-center space-x-1.5">
                    <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Online Coders</span>
                    <span className="relative flex h-2 w-2">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                    </span>
                  </div>
                  <div className="text-3xl font-extrabold text-white">
                    {statsLoading ? '...' : stats.liveUsers}
                  </div>
                </div>
                <div className="bg-accentBlue/10 p-3 rounded-md border border-accentBlue/25 text-accentBlue group-hover:bg-accentBlue/20 transition-all">
                  <Activity className="w-6 h-6" />
                </div>
              </div>
            </div>

            {/* Premium custom SVG charts */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 pt-2">
              
              {/* Chart 1: Registration Area Chart */}
              <div className="bg-darkCard border border-darkBorder p-6 rounded-2xl space-y-4 shadow-lg">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-black uppercase text-slate-400 tracking-widest flex items-center">
                    <Users className="w-4 h-4 text-accentBlue mr-2" /> User Registrations Trend
                  </h3>
                  <span className="text-[10px] bg-accentBlue/15 text-accentBlue border border-accentBlue/20 px-2 py-0.5 rounded font-bold uppercase tracking-wider">Weekly Growth</span>
                </div>
                <div className="h-56 w-full flex items-center justify-center pt-2">
                  {renderAreaChart()}
                </div>
              </div>

              {/* Chart 2: Workload Bar Chart */}
              <div className="bg-darkCard border border-darkBorder p-6 rounded-2xl space-y-4 shadow-lg">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-black uppercase text-slate-400 tracking-widest flex items-center">
                    <Send className="w-4 h-4 text-accentBlue mr-2" /> Compilation Workload
                  </h3>
                  <span className="text-[10px] bg-accentBlue/15 text-accentBlue border border-accentBlue/20 px-2 py-0.5 rounded font-bold uppercase tracking-wider">Language Share</span>
                </div>
                <div className="h-56 w-full flex items-center justify-center pt-2">
                  {renderBarChart()}
                </div>
              </div>

            </div>
          </div>
        )}

        {/* VIEW 2: Manage Questions Table tab */}
        {activeTab === 'questions' && (
          <div className="space-y-6">
            
            {/* Table Header Section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-darkBorder pb-5">
              <div>
                <h1 className="text-3xl font-black text-white tracking-wide">Manage Question Bank</h1>
                <p className="text-xs text-slate-400 mt-0.5">Configure parameters, edit metadata, or delete challenges by domain</p>
              </div>

              {/* Search Challenge input */}
              <div className="relative w-full md:w-80">
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search questions by statement or topic..."
                  className="w-full bg-darkCard border border-darkBorder px-4 py-2.5 rounded-xl text-xs focus:outline-none focus:border-accentBlue text-slate-200 font-semibold"
                />
              </div>
            </div>

            {/* Domain Tabs Bar */}
            <div className="flex flex-wrap items-center gap-2 border-b border-darkBorder/40 pb-2 select-none">
              {[
                { id: 'coding', label: 'Coding Challenges', icon: '💻' },
                { id: 'aptitude', label: 'Aptitude MCQs', icon: '🧠' },
                { id: 'verbal', label: 'Verbal Ability', icon: '🗣️' },
                { id: 'all', label: 'All Domains', icon: '🌐' }
              ].map(tab => (
                <button
                  key={tab.id}
                  type="button"
                  onClick={() => setDomainFilter(tab.id)}
                  className={`px-4 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider transition-all border cursor-pointer ${
                    domainFilter === tab.id
                      ? 'bg-accentBlue/10 border-accentBlue text-accentBlue shadow-sm shadow-accentBlue/5'
                      : 'bg-transparent border-transparent text-slate-400 hover:text-slate-200 hover:bg-darkBg/60'
                  }`}
                >
                  <span className="mr-1.5">{tab.icon}</span>
                  {tab.label}
                </button>
              ))}
            </div>

            {error && (
              <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl text-sm">
                {error}
              </div>
            )}

            {loading ? (
              <div className="p-16 flex flex-col items-center justify-center space-y-3">
                <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-accentBlue"></div>
                <span className="text-xs text-slate-400 font-bold uppercase tracking-widest">Querying database...</span>
              </div>
            ) : filteredQuestions.length === 0 ? (
              <div className="text-center py-20 bg-darkCard border border-darkBorder rounded-2xl text-slate-500 space-y-3">
                <Settings className="w-12 h-12 mx-auto text-slate-700 animate-spin" style={{ animationDuration: '6s' }} />
                <p className="text-sm font-bold">No questions match your filter query.</p>
              </div>
            ) : (
              <div className="bg-darkCard border border-darkBorder rounded-2xl overflow-hidden shadow-xl">
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-darkBg/60 border-b border-darkBorder/80 text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                        <th className="py-4 px-6">Title</th>
                        <th className="py-4 px-6">Company</th>
                        <th className="py-4 px-6">Topic</th>
                        <th className="py-4 px-6">Difficulty</th>
                        <th className="py-4 px-6 text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-darkBorder/40">
                      {filteredQuestions.map((q) => (
                        <tr
                          key={q._id}
                          className="hover:bg-darkBg/20 transition-colors"
                        >
                          <td className="py-4 px-6 font-extrabold text-slate-200 text-sm tracking-wide max-w-xs truncate" title={q.title || q.content?.statement}>
                            {q.title || q.content?.statement || 'Untitled Question'}
                          </td>
                          <td className="py-4 px-6">
                            {q.company && q.company.length > 0 ? (
                              <div className="flex gap-1 flex-wrap">
                                {q.company.map((c) => (
                                  <span
                                    key={c}
                                    className="text-[9px] bg-darkBg border border-darkBorder px-1.5 py-0.5 rounded text-slate-400 font-bold"
                                  >
                                    {c}
                                  </span>
                                ))}
                              </div>
                            ) : (
                              <span className="text-xs text-slate-500">—</span>
                            )}
                          </td>
                          <td className="py-4 px-6">
                            <span className="text-xs text-slate-400 flex items-center">
                              <Tag className="w-3 h-3 text-slate-500 mr-1.5 shrink-0" />
                              {q.topic}
                            </span>
                          </td>
                          <td className="py-4 px-6">
                            <span className={`text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded border ${getDifficultyColor(q.difficulty)}`}>
                              {q.difficulty}
                            </span>
                          </td>
                          <td className="py-4 px-6">
                            <div className="flex items-center justify-center space-x-2.5">
                              <button
                                onClick={() => handleEdit(q._id)}
                                className="p-2 text-amber-400 hover:text-amber-300 hover:bg-amber-500/10 rounded-lg border border-transparent hover:border-amber-500/20 transition-all"
                                title="Edit Question"
                              >
                                <Edit2 className="w-4 h-4" />
                              </button>
                               <button
                                onClick={() => handleDelete(q._id, q.title || q.content?.statement || 'this question')}
                                className="p-2 text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 rounded-lg border border-transparent hover:border-rose-500/20 transition-all"
                                title="Delete Question"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}

        {/* VIEW 3: Embedded Add/Edit wizard form */}
        {activeTab === 'add_question' && (
          <div className="space-y-6">
            <AdminQuestionForm
              editId={editQuestionId}
              onSave={() => {
                setEditQuestionId(null);
                setActiveTab('questions');
                fetchQuestions();
                fetchStats();
              }}
              onCancel={() => {
                setEditQuestionId(null);
                setActiveTab('questions');
              }}
            />
          </div>
        )}

        {/* VIEW 4: Manage Tracks list view */}
        {activeTab === 'manage_tracks' && !isTrackFormActive && (
          <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-darkBorder pb-5">
              <div>
                <h1 className="text-3xl font-black text-white tracking-wide">Manage Learning Tracks</h1>
                <p className="text-xs text-slate-400 mt-0.5">Review, edit, and orchestrate practice paths or monthly company tracks</p>
              </div>

              <button
                onClick={handleCreateTrackClick}
                className="bg-accentBlue hover:bg-accentBlue/90 text-white px-5 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider flex items-center space-x-1.5 shadow-lg shadow-accentBlue/20 transition-all self-start md:self-auto"
              >
                <Plus className="w-4 h-4" />
                <span>Create Track</span>
              </button>
            </div>

            {tracksError && (
              <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl text-sm">
                {tracksError}
              </div>
            )}

            {tracksLoading ? (
              <div className="p-16 flex flex-col items-center justify-center space-y-3">
                <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-accentBlue"></div>
                <span className="text-xs text-slate-400 font-bold uppercase tracking-widest">Querying practice modules...</span>
              </div>
            ) : tracks.length === 0 ? (
              <div className="text-center py-20 bg-darkCard border border-darkBorder rounded-lg text-slate-500 space-y-3">
                <Compass className="w-12 h-12 mx-auto text-slate-700 animate-spin" style={{ animationDuration: '8s' }} />
                <p className="text-sm font-bold">No tracks configured yet. Click "Create Track" to begin.</p>
              </div>
            ) : (
              <div className="bg-darkCard border border-darkBorder rounded-lg overflow-hidden shadow-xl">
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-darkBg/60 border-b border-darkBorder/80 text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                        <th className="py-4 px-6">Track Title</th>
                        <th className="py-4 px-6">Type</th>
                        <th className="py-4 px-6">Company / Category</th>
                        <th className="py-4 px-6 text-center">Mode</th>
                        <th className="py-4 px-6 text-center">Month</th>
                        <th className="py-4 px-6 text-center">Challenges</th>
                        <th className="py-4 px-6 text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-darkBorder/40">
                      {tracks.map((t) => (
                        <tr
                          key={t._id}
                          className="hover:bg-darkBg/20 transition-colors"
                        >
                          <td className="py-4 px-6 font-extrabold text-slate-200 text-sm tracking-wide">
                            <div className="font-extrabold text-slate-200">{t.title}</div>
                            {t.description && (
                              <div className="text-[10px] text-slate-400 font-medium truncate max-w-xs mt-0.5">{t.description}</div>
                            )}
                          </td>
                          <td className="py-4 px-6">
                            <span className={`text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded border ${
                              t.type === 'company' 
                                ? 'text-accentBlue border-accentBlue/25 bg-accentBlue/10'
                                : 'text-slate-300 border-darkBorder bg-darkBg/60'
                            }`}>
                              {t.type}
                            </span>
                          </td>
                          <td className="py-4 px-6">
                            {t.type === 'company' ? (
                              <div className="flex items-center space-x-1.5">
                                <span className="text-xs font-bold text-slate-300">{t.company}</span>
                                <span className="text-[9px] text-slate-500 bg-darkBg border border-darkBorder px-1 py-0.5 rounded capitalize">{t.category}</span>
                              </div>
                            ) : (
                              <span className="text-xs text-slate-500">—</span>
                            )}
                          </td>
                          <td className="py-4 px-6 text-center">
                            {t.isAutoGenerated ? (
                              <span className="text-[8px] font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded uppercase">Auto</span>
                            ) : (
                              <span className="text-[8px] font-bold text-amber-400 bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 rounded uppercase">Curated</span>
                            )}
                          </td>
                          <td className="py-4 px-6 text-center text-xs text-slate-300">
                            {t.month || <span className="text-slate-500">—</span>}
                          </td>
                          <td className="py-4 px-6 text-center text-xs font-bold text-slate-200">
                            {t.totalQuestions}
                          </td>
                          <td className="py-4 px-6">
                            <div className="flex items-center justify-center space-x-2.5">
                              <button
                                onClick={() => handleEditTrackClick(t)}
                                className="p-2 text-amber-400 hover:text-amber-300 hover:bg-amber-500/10 rounded-lg border border-transparent hover:border-amber-500/20 transition-all"
                                title="Edit Track"
                              >
                                <Edit2 className="w-4 h-4" />
                              </button>
                              <button
                                onClick={() => handleDeleteTrack(t._id, t.title)}
                                className="p-2 text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 rounded-lg border border-transparent hover:border-rose-500/20 transition-all"
                                title="Delete Track"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}

        {/* VIEW 5: Embedded Track Add/Edit wizard form */}
        {activeTab === 'manage_tracks' && isTrackFormActive && (
          <div className="space-y-6">
            <div className="border-b border-darkBorder pb-4">
              <h1 className="text-3xl font-black text-white tracking-wide">
                {editTrackId ? 'Modify Practice Track' : 'Assemble Practice Track'}
              </h1>
              <p className="text-xs text-slate-400 mt-0.5">Define metadata and map challenge paths or configure auto generation criteria</p>
            </div>

            <form onSubmit={handleSaveTrack} className="bg-darkCard border border-darkBorder rounded-2xl p-6 space-y-6 shadow-xl relative overflow-hidden">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Track Title */}
                <div className="space-y-2">
                  <label className="text-xs font-bold uppercase tracking-wider text-slate-300">Track Title *</label>
                  <input
                    type="text"
                    required
                    value={trackTitle}
                    onChange={(e) => setTrackTitle(e.target.value)}
                    placeholder="e.g. TCS POTM June, Amazon Product Track, Stack Roadmap"
                    className="w-full bg-darkBg border border-darkBorder px-4 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accentBlue text-slate-200"
                  />
                </div>

                {/* Track Type */}
                <div className="space-y-2">
                  <label className="text-xs font-bold uppercase tracking-wider text-slate-300">Track Type *</label>
                  <select
                    value={trackType}
                    onChange={(e) => {
                      setTrackType(e.target.value);
                      if (e.target.value === 'topic') {
                        setTrackIsAutoGenerated(false);
                      }
                    }}
                    className="w-full bg-darkBg border border-darkBorder px-4 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accentBlue text-slate-200"
                  >
                    <option value="company">Company Track</option>
                    <option value="topic">Topic Track</option>
                  </select>
                </div>

                {/* Description */}
                <div className="md:col-span-2 space-y-2">
                  <label className="text-xs font-bold uppercase tracking-wider text-slate-300">Description</label>
                  <textarea
                    rows="3"
                    value={trackDescription}
                    onChange={(e) => setTrackDescription(e.target.value)}
                    placeholder="Describe what skills/questions are covered in this track..."
                    className="w-full bg-darkBg border border-darkBorder px-4 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accentBlue text-slate-200"
                  />
                </div>

                {/* Company Tracks Specific Configs */}
                {trackType === 'company' && (
                  <>
                    {/* Target Company Name */}
                    <div className="space-y-2">
                      <label className="text-xs font-bold uppercase tracking-wider text-slate-300">Target Company</label>
                      <input
                        type="text"
                        value={trackCompany}
                        onChange={(e) => setTrackCompany(e.target.value)}
                        placeholder="e.g. TCS, Infosys, Amazon"
                        className="w-full bg-darkBg border border-darkBorder px-4 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accentBlue text-slate-200"
                      />
                    </div>

                    {/* Company Category */}
                    <div className="space-y-2">
                      <label className="text-xs font-bold uppercase tracking-wider text-slate-300">Company Category</label>
                      <select
                        value={trackCategory}
                        onChange={(e) => setTrackCategory(e.target.value)}
                        className="w-full bg-darkBg border border-darkBorder px-4 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accentBlue text-slate-200"
                      >
                        <option value="service">Service-Based (TCS, Infosys, etc.)</option>
                        <option value="product">Product-Based (Amazon, Google, etc.)</option>
                      </select>
                    </div>

                    {/* Target Month / Schedule Info */}
                    <div className="space-y-2">
                      <label className="text-xs font-bold uppercase tracking-wider text-slate-300">Month / Challenge Tag</label>
                      <input
                        type="text"
                        value={trackMonth}
                        onChange={(e) => setTrackMonth(e.target.value)}
                        placeholder="e.g. June POTM, Monthly Challenge"
                        className="w-full bg-darkBg border border-darkBorder px-4 py-2.5 rounded-xl text-sm focus:outline-none focus:border-accentBlue text-slate-200"
                      />
                    </div>

                    {/* Auto Generated Toggle Switch */}
                    <div className="flex items-center space-x-3 pt-6">
                      <input
                        type="checkbox"
                        id="isAutoGenerated"
                        checked={trackIsAutoGenerated}
                        onChange={(e) => setTrackIsAutoGenerated(e.target.checked)}
                        className="w-4 h-4 rounded border-darkBorder text-accentBlue focus:ring-0 cursor-pointer bg-darkBg"
                      />
                      <label htmlFor="isAutoGenerated" className="text-xs font-bold uppercase tracking-wider text-slate-300 cursor-pointer select-none">
                        Auto Generate Questions
                      </label>
                      <p className="text-[10px] text-slate-400 block ml-2">
                        (Fetches random unsolved questions based on profile company & category fallbacks)
                      </p>
                    </div>
                  </>
                )}

              </div>

              {/* Questions Manual Selection list */}
              {(!trackIsAutoGenerated || trackType === 'topic') && (
                <div className="pt-4 border-t border-darkBorder/40 space-y-4">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div>
                      <label className="text-xs font-bold uppercase tracking-wider text-slate-300">
                        Link Challenges ({trackQuestions.length} Selected)
                      </label>
                      <p className="text-[10px] text-slate-400">Search and check questions to include in this learning track roadmap</p>
                    </div>
                    
                    <input
                      type="text"
                      value={trackQuestionSearch}
                      onChange={(e) => setTrackQuestionSearch(e.target.value)}
                      placeholder="Filter questions by title or topic..."
                      className="bg-darkBg border border-darkBorder px-4 py-1.5 rounded-xl text-xs focus:outline-none focus:border-accentBlue text-slate-200 w-full sm:w-64"
                    />
                  </div>

                  <div className="max-h-60 overflow-y-auto border border-darkBorder rounded-xl divide-y divide-darkBorder bg-darkBg">
                    {questions
                      .filter(q => 
                        (q.title || q.content?.statement || '').toLowerCase().includes(trackQuestionSearch.toLowerCase()) ||
                        (q.topic || '').toLowerCase().includes(trackQuestionSearch.toLowerCase())
                      )
                      .map(q => {
                        const isChecked = trackQuestions.includes(q._id);
                        return (
                          <div 
                            key={q._id}
                            onClick={() => {
                              if (isChecked) {
                                setTrackQuestions(prev => prev.filter(id => id !== q._id));
                              } else {
                                setTrackQuestions(prev => [...prev, q._id]);
                              }
                            }}
                            className="flex items-center space-x-3 px-4 py-3 hover:bg-darkCard/50 cursor-pointer select-none transition-colors"
                          >
                            <input
                              type="checkbox"
                              checked={isChecked}
                              readOnly
                              className="w-4 h-4 rounded border-darkBorder text-accentBlue cursor-pointer bg-darkBg"
                            />
                            <div className="flex-grow min-w-0">
                              <div className="text-xs font-extrabold text-slate-200 truncate">{q.title || q.content?.statement || 'Untitled Question'}</div>
                              <div className="flex items-center space-x-2 text-[9px] text-slate-500 font-bold mt-0.5">
                                <span className="uppercase">{q.topic}</span>
                                <span>•</span>
                                <span className={`uppercase ${
                                  q.difficulty === 'Easy' ? 'text-emerald-400' :
                                  q.difficulty === 'Medium' ? 'text-amber-400' : 'text-rose-400'
                                }`}>{q.difficulty}</span>
                              </div>
                            </div>
                          </div>
                        );
                      })
                    }
                  </div>
                </div>
              )}

              {/* Form Action Controls */}
              <div className="pt-4 border-t border-darkBorder/40 flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => {
                    setIsTrackFormActive(false);
                    setEditTrackId(null);
                  }}
                  className="bg-darkBg border border-darkBorder hover:bg-darkBg/60 px-5 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider text-slate-300 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-accentBlue hover:bg-accentBlue/90 text-white px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider shadow-lg shadow-accentBlue/20 transition-all"
                >
                  {editTrackId ? 'Save Track' : 'Create Track'}
                </button>
              </div>

            </form>
          </div>
        )}

        {/* VIEW 6: Feedback List View */}
        {activeTab === 'feedback' && (
          <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-darkBorder pb-5">
              <div>
                <h1 className="text-3xl font-black text-white tracking-wide">User Feedback & Bug Reports</h1>
                <p className="text-xs text-slate-400 mt-0.5">Review issues reported by users and update their resolution status</p>
              </div>

              {/* Filter tickets select */}
              <div className="flex items-center space-x-3 self-start md:self-auto">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Filter:</span>
                <select
                  value={feedbackFilter}
                  onChange={(e) => setFeedbackFilter(e.target.value)}
                  className="bg-darkCard border border-darkBorder px-3 py-1.5 rounded-xl text-xs focus:outline-none focus:border-accentBlue text-slate-200"
                >
                  <option value="all">All Submissions</option>
                  <option value="feedback">Feedback Only</option>
                  <option value="bug">Bugs Only</option>
                  <option value="general">Inquiries Only</option>
                </select>
              </div>
            </div>

            {feedbackError && (
              <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl text-sm">
                {feedbackError}
              </div>
            )}

            {feedbackLoading ? (
              <div className="p-16 flex flex-col items-center justify-center space-y-3">
                <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-accentBlue"></div>
                <span className="text-xs text-slate-400 font-bold uppercase tracking-widest">Querying submissions...</span>
              </div>
            ) : feedbacks.length === 0 ? (
              <div className="text-center py-20 bg-darkCard border border-darkBorder rounded-xl text-slate-500 space-y-3">
                <MessageSquare className="w-12 h-12 mx-auto text-slate-700 animate-pulse" />
                <p className="text-sm font-bold">No feedback or bug reports submitted yet.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {feedbacks
                  .filter(item => feedbackFilter === 'all' || item.type === feedbackFilter)
                  .map((item) => (
                    <div 
                      key={item._id} 
                      className={`bg-darkCard border rounded-2xl p-6 shadow-xl space-y-4 transition-all relative overflow-hidden ${
                        item.status === 'resolved' 
                          ? 'border-emerald-500/10 opacity-70' 
                          : item.type === 'bug'
                            ? 'border-rose-500/10 hover:border-rose-500/20'
                            : 'border-darkBorder hover:border-accentBlue/20'
                      }`}
                    >
                      {/* Ticket Header */}
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                        <div className="flex items-center space-x-2.5">
                          {/* Type Badge */}
                          <span className={`text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded border ${
                            item.type === 'bug' 
                              ? 'text-rose-400 border-rose-500/25 bg-rose-500/10'
                              : item.type === 'general'
                                ? 'text-sky-400 border-sky-500/25 bg-sky-500/10'
                                : 'text-indigo-400 border-indigo-500/25 bg-indigo-500/10'
                          }`}>
                            {item.type === 'bug' ? 'Bug Report' : item.type === 'general' ? 'General Enquiry' : 'Feedback'}
                          </span>

                          {/* Status Badge with Select */}
                          <div className="relative inline-flex">
                            <select
                              value={item.status}
                              onChange={(e) => handleStatusChange(item._id, e.target.value)}
                              className={`text-[9px] font-black uppercase tracking-widest px-2.5 py-0.5 rounded border cursor-pointer focus:outline-none appearance-none pr-6 ${
                                item.status === 'resolved'
                                  ? 'text-emerald-400 border-emerald-500/25 bg-emerald-500/10'
                                  : item.status === 'reviewed'
                                    ? 'text-amber-400 border-amber-500/25 bg-amber-500/10'
                                    : 'text-rose-400 border-rose-500/25 bg-rose-500/10'
                              }`}
                            >
                              <option value="pending">Pending</option>
                              <option value="reviewed">Reviewed</option>
                              <option value="resolved">Resolved</option>
                            </select>
                            <span className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[9px] font-extrabold pointer-events-none opacity-65">▾</span>
                          </div>
                        </div>

                        {/* Date info */}
                        <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">
                          Submitted {new Date(item.createdAt).toLocaleString()}
                        </span>
                      </div>

                      {/* Ticket Content */}
                      <div className="space-y-1">
                        <h3 className="text-base font-extrabold text-white tracking-wide">
                          {item.subject}
                        </h3>
                        <p className="text-xs text-slate-400 whitespace-pre-wrap leading-relaxed">
                          {item.message}
                        </p>
                      </div>

                      {/* Submitter Details / Footer */}
                      <div className="pt-4 border-t border-darkBorder/40 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs">
                        <div className="flex items-center space-x-2 text-slate-400 font-medium">
                          <span>Submitter:</span>
                          <span className="text-white font-bold">{item.name}</span>
                          <span className="text-slate-500">•</span>
                          <span className="text-slate-300 font-bold">{item.email}</span>
                          {item.user && (
                            <>
                              <span className="text-slate-500">•</span>
                              <span className="text-indigo-400 font-bold bg-[#6366F1]/10 px-2 py-0.5 rounded border border-[#6366F1]/15 text-[10px] uppercase">Registered User</span>
                            </>
                          )}
                        </div>

                        {/* Action buttons */}
                        <div className="flex items-center space-x-3 self-end sm:self-auto">
                          <button
                            onClick={() => handleDeleteFeedback(item._id)}
                            className="p-2 text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 rounded-lg border border-transparent hover:border-rose-500/20 transition-all flex items-center space-x-1"
                            title="Delete Ticket"
                          >
                            <Trash2 className="w-4 h-4" />
                            <span className="text-[10px] font-bold uppercase tracking-wider">Delete</span>
                          </button>
                        </div>
                      </div>

                    </div>
                  ))}
              </div>
            )}
          </div>
        )}

        {/* VIEW 6: Manage Resources */}
        {activeTab === 'manage_resources' && (
          <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-darkBorder pb-5">
              <div>
                <h1 className="text-3xl font-black text-white tracking-wide">Manage Resources</h1>
                <p className="text-xs text-slate-400 mt-0.5">Add, edit, or remove study material links shown on the Home page</p>
              </div>
              {!resFormActive && (
                <button
                  onClick={() => { setEditResId(null); setResTitle(''); setResIcon('Database'); setResDriveLink(''); setResFormActive(true); }}
                  className="bg-accentBlue hover:bg-accentBlue/90 text-white px-5 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider flex items-center space-x-1.5 shadow-lg shadow-accentBlue/20 transition-all self-start md:self-auto"
                >
                  <Plus className="w-4 h-4" />
                  <span>Add Resource</span>
                </button>
              )}
            </div>

            {resError && (
              <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl text-sm">{resError}</div>
            )}

            {/* Add / Edit Form */}
            {resFormActive && (
              <div className="bg-darkCard border border-darkBorder rounded-2xl p-6 space-y-5 shadow-xl">
                <h2 className="text-sm font-black text-white uppercase tracking-wider">
                  {editResId ? 'Edit Resource' : 'Add New Resource'}
                </h2>
                <form onSubmit={handleSaveRes} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <label className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Resource Name *</label>
                      <input
                        type="text"
                        value={resTitle}
                        onChange={e => setResTitle(e.target.value)}
                        placeholder="e.g. SQL Notes"
                        className="w-full bg-darkBg border border-darkBorder px-3.5 py-2.5 rounded-xl text-xs focus:outline-none focus:border-accentBlue text-slate-200"
                        required
                      />
                    </div>
                    <div className="space-y-1.5">
                      <label className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Icon</label>
                      <select
                        value={resIcon}
                        onChange={e => setResIcon(e.target.value)}
                        className="w-full bg-darkBg border border-darkBorder px-3.5 py-2.5 rounded-xl text-xs focus:outline-none focus:border-accentBlue text-slate-200"
                      >
                        <option value="Database">Database</option>
                        <option value="Server">Server</option>
                        <option value="Network">Network</option>
                        <option value="Layers">Layers</option>
                        <option value="FileText">FileText</option>
                        <option value="BookOpen">BookOpen</option>
                      </select>
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[10px] uppercase font-bold text-slate-400 tracking-wider flex items-center gap-1.5">
                      <Link2 className="w-3 h-3" /> Google Drive Link
                    </label>
                    <input
                      type="url"
                      value={resDriveLink}
                      onChange={e => setResDriveLink(e.target.value)}
                      placeholder="https://drive.google.com/drive/folders/..."
                      className="w-full bg-darkBg border border-darkBorder px-3.5 py-2.5 rounded-xl text-xs focus:outline-none focus:border-accentBlue text-slate-200 font-mono"
                    />
                    <p className="text-[10px] text-slate-500">Paste the Google Drive folder link. Users will be taken directly to this URL.</p>
                  </div>
                  <div className="flex items-center gap-3 pt-2">
                    <button
                      type="submit"
                      className="bg-accentBlue hover:bg-accentBlue/90 text-white px-5 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider flex items-center space-x-1.5 shadow-lg shadow-accentBlue/20 transition-all cursor-pointer"
                    >
                      {editResId ? <><Edit2 className="w-3.5 h-3.5" /><span>Update Resource</span></> : <><Plus className="w-3.5 h-3.5" /><span>Save Resource</span></>}
                    </button>
                    <button
                      type="button"
                      onClick={() => { setResFormActive(false); setEditResId(null); }}
                      className="bg-transparent border border-darkBorder hover:border-slate-500/30 hover:bg-darkBg/60 text-slate-300 hover:text-white px-5 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer"
                    >
                      Cancel
                    </button>
                  </div>
                </form>
              </div>
            )}

            {/* Resources Table */}
            {resLoading ? (
              <div className="p-16 flex flex-col items-center justify-center space-y-3">
                <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-accentBlue"></div>
                <span className="text-xs text-slate-400 font-bold uppercase tracking-widest">Loading resources...</span>
              </div>
            ) : resCategories.length === 0 ? (
              <div className="text-center py-20 bg-darkCard border border-darkBorder rounded-lg text-slate-500 space-y-3">
                <FolderOpen className="w-12 h-12 mx-auto text-slate-700" />
                <p className="text-sm font-bold">No resources added yet. Click "Add Resource" to create one.</p>
              </div>
            ) : (
              <div className="bg-darkCard border border-darkBorder rounded-2xl overflow-hidden shadow-xl">
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-darkBg/60 border-b border-darkBorder/80 text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                        <th className="py-4 px-6">Name</th>
                        <th className="py-4 px-6">Icon</th>
                        <th className="py-4 px-6">Drive Link</th>
                        <th className="py-4 px-6 text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-darkBorder/40">
                      {resCategories.map(r => (
                        <tr key={r._id} className="hover:bg-darkBg/20 transition-colors">
                          <td className="py-4 px-6 font-extrabold text-slate-200 text-sm">{r.title}</td>
                          <td className="py-4 px-6">
                            <span className="text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded border text-accentBlue border-accentBlue/25 bg-accentBlue/10">
                              {r.icon || 'Database'}
                            </span>
                          </td>
                          <td className="py-4 px-6 max-w-xs">
                            {r.driveFolderLink ? (
                              <a
                                href={r.driveFolderLink}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-xs text-accentBlue hover:underline font-mono truncate block max-w-[240px]"
                              >
                                {r.driveFolderLink}
                              </a>
                            ) : (
                              <span className="text-xs text-slate-500 italic">No link set</span>
                            )}
                          </td>
                          <td className="py-4 px-6">
                            <div className="flex items-center justify-center space-x-2.5">
                              <button
                                onClick={() => handleEditRes(r)}
                                className="p-2 text-amber-400 hover:text-amber-300 hover:bg-amber-500/10 rounded-lg border border-transparent hover:border-amber-500/20 transition-all"
                                title="Edit Resource"
                              >
                                <Edit2 className="w-4 h-4" />
                              </button>
                              <button
                                onClick={() => handleDeleteRes(r._id, r.title)}
                                className="p-2 text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 rounded-lg border border-transparent hover:border-rose-500/20 transition-all"
                                title="Delete Resource"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}

      </main>

      
    </div>
  );
};

export default AdminDashboard;
