import mongoose from 'mongoose';

const trackSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  type: {
    type: String,
    enum: ['company', 'topic'],
    required: true
  },
  category: {
    type: String,
    enum: ['service', 'product']
  },
  company: {
    type: String
  },
  topic: {
    type: String
  },
  month: {
    type: String
  },
  questions: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Question'
  }],
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, { timestamps: true });

const Track = mongoose.model('Track', trackSchema);
export default Track;
